### ISSUE TITLE
Error Standalone mode: Cannot find module 'blog'

### ISSUE THREAD

**Issue by MIKAGMR** [nuxt/press#57]
When I try to use the standalone mode:
```
export default {
  modules: ['@nuxt/press','blog']
}
```

I get these errors: 
```
 FATAL  Cannot find module 'blog'                                                                                                                                                                                             11:41:13
Require stack:
- /Users/michael/WebstormProjects/prototypes/nuxtpress/node_modules/@nuxt/core/dist/core.js
- /Users/michael/WebstormProjects/prototypes/nuxtpress/node_modules/@nuxt/cli/dist/cli-command.js
- /Users/michael/WebstormProjects/prototypes/nuxtpress/node_modules/@nuxt/cli/dist/cli.js
- /Users/michael/WebstormProjects/prototypes/nuxtpress/node_modules/nuxt/bin/nuxt.js

  Error: Cannot find module 'blog'
  Require stack:
  - node_modules/@nuxt/core/dist/core.js
  - node_modules/@nuxt/cli/dist/cli-command.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:627:31)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:163:36)
  at node_modules/@nuxt/utils/dist/utils.js:1796:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:42:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:709:5)
```

I copied the posts, pages directories and the nuxt-press.json from the example/blog directory.

**Comment by MIKAGMR** [comment]
Thanks. The documentation of the standalone mode should be updated.

Is it ok when I correct this part in the documentation and do a commit?

**Comment by MIKAGMR** [comment]
@galvez Sorry, you are right.
