### ISSUE TITLE
nuxt generate gives error `Error: Cannot find module 'dist/_press/sources/test'`

### ISSUE THREAD

**Issue by nskoretz** [nuxt/press#62]
I am trying to whip up a website that contains content written in Markdown and I decided to use nuxt/press to show it. It has been working fine with .md files in pages when using `npm run dev`, barring some warnings.

Although when running `npm run generate` I get the following error trace:

```
$ npm run generate

> nuxt-nsk@1.0.0 generate /home/nskoretz/Documents/Projects/nuxt-nsk
> nuxt generate


 WARN  devModules has been renamed to buildModules and will be removed in Nuxt 3.                                                                                                                                      19:01:54

ℹ Production build                                                                                                                                                                                                     19:01:56

 WARN  Missing or invalid publication date in README -- see documentation at https://nuxt.press                                                                                                                        19:01:57


 WARN  Missing or invalid publication date in README -- see documentation at https://nuxt.press (repeated 8 times)                                                                                                     19:01:57


 WARN  Missing or invalid publication date in CHANGELOG -- see documentation at https://nuxt.press                                                                                                                     19:01:57

✔ Builder initialized                                                                                                                                                                                                  19:01:57
✔ Nuxt files generated                                                                                                                                                                                                 19:01:57

✔ Client
  Compiled successfully in 10.05s

✔ Server
  Compiled successfully in 2.95s


Hash: f0f67cb15f29465beb7d
Version: webpack 4.39.3
Time: 10057ms
Built at: 09/10/2019 7:02:10 PM
                         Asset       Size  Chunks             Chunk Names
../server/client.manifest.json   12.5 KiB          [emitted]  
       107d8ba597db4d3b6c26.js   1.07 KiB      10  [emitted]  
       39d74df9691aa65ba659.js   33.9 KiB       7  [emitted]  vendors.app
       3c22acde401ee18a263c.js   1.55 KiB       2  [emitted]  pages/About
       48c58431996d9a6ffa7b.js   1.05 KiB       8  [emitted]  
       4ad111496a5d8ce2f842.js   1.29 KiB       9  [emitted]  
       51bd439c33cc138a80e3.js   3.64 KiB       4  [emitted]  pages/index
       56c4f30524cf7557a367.js   2.45 KiB       6  [emitted]  runtime
       5f424772e7482ecda65c.js    214 KiB       1  [emitted]  commons.app
       65da1c1eb94d066dbd7b.js   52.1 KiB       0  [emitted]  app
       74cf6484512c1a6e498b.js  257 bytes       3  [emitted]  pages/ansible/Aindex
                      LICENSES  547 bytes          [emitted]  
       d77ae9009ad6bf99e37a.js   1.48 KiB       5  [emitted]  pages/term/index
              img/3dc5aeb.jpeg   39.8 KiB          [emitted]  
 + 2 hidden assets
Entrypoint app = 56c4f30524cf7557a367.js 5f424772e7482ecda65c.js 39d74df9691aa65ba659.js 65da1c1eb94d066dbd7b.js

Hash: fe47cd2a4f2821b76760
Version: webpack 4.39.3
Time: 2942ms
Built at: 09/10/2019 7:02:13 PM
                  Asset       Size  Chunks             Chunk Names
27eeb12b349ed908e716.js  877 bytes       6  [emitted]  
28daba9681f78feea7da.js  285 bytes       2  [emitted]  pages/ansible/Aindex
4861ff1307694e89144d.js   1.41 KiB       1  [emitted]  pages/About
68afc30d909ceb49b4b3.js   1.37 KiB       4  [emitted]  pages/term/index
89378ec790dcc1eb581f.js   1.01 KiB       7  [emitted]  
8acd3b343c3070b5ad4a.js   3.79 KiB       3  [emitted]  pages/index
8df51c9bb898e9ecdae2.js  802 bytes       5  [emitted]  
              server.js   55.2 KiB       0  [emitted]  app
   server.manifest.json  963 bytes          [emitted]  
 + 8 hidden assets
Entrypoint app = server.js server.js.map

 ERROR  Cannot find module '/home/nskoretz/Documents/Projects/nuxt-nsk/dist/_press/sources/test'                                                                                                                       19:02:13
Require stack:
- /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/press/dist/nuxt-press.js
- /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/core/dist/core.js
- /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/cli/dist/cli-command.js
- /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/cli/dist/cli.js
- /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/nuxt/bin/nuxt.js

  Error: Cannot find module 'dist/_press/sources/test'
  Require stack:
  - node_modules/@nuxt/press/dist/nuxt-press.js
  - node_modules/@nuxt/core/dist/core.js
  - node_modules/@nuxt/cli/dist/cli-command.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at node_modules/@nuxt/press/dist/nuxt-press.js:85:90
  at new Promise (<anonymous>)
  at importModule (node_modules/@nuxt/press/dist/nuxt-press.js:85:31)
  at Object.keys.map (node_modules/@nuxt/press/dist/nuxt-press.js:461:24)
  at Array.map (<anonymous>)
  at ModuleContainer.generateRoutes (node_modules/@nuxt/press/dist/nuxt-press.js:459:36)
  at distCopied (node_modules/@nuxt/press/dist/nuxt-press.js:1829:57)


 FATAL  Cannot find module '/home/nskoretz/Documents/Projects/nuxt-nsk/dist/_press/sources/test'                                                                                                                       19:02:13
Require stack:
- /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/press/dist/nuxt-press.js
- /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/core/dist/core.js
- /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/cli/dist/cli-command.js
- /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/cli/dist/cli.js
- /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/nuxt/bin/nuxt.js

  Error: Cannot find module 'dist/_press/sources/test'
  Require stack:
  - node_modules/@nuxt/press/dist/nuxt-press.js
  - node_modules/@nuxt/core/dist/core.js
  - node_modules/@nuxt/cli/dist/cli-command.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at node_modules/@nuxt/press/dist/nuxt-press.js:85:90
  at new Promise (<anonymous>)
  at importModule (node_modules/@nuxt/press/dist/nuxt-press.js:85:31)
  at Object.keys.map (node_modules/@nuxt/press/dist/nuxt-press.js:461:24)
  at Array.map (<anonymous>)
  at ModuleContainer.generateRoutes (node_modules/@nuxt/press/dist/nuxt-press.js:459:36)
  at distCopied (node_modules/@nuxt/press/dist/nuxt-press.js:1829:57)


   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                     │
   │   ✖ Nuxt Fatal Error                                                                                │
   │                                                                                                     │
   │   Error: Cannot find module '/home/nskoretz/Documents/Projects/nuxt-nsk/dist/_press/sources/test'   │
   │   Require stack:                                                                                    │
   │   - /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/press/dist/nuxt-press.js          │
   │   - /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/core/dist/core.js                 │
   │   - /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/cli/dist/cli-command.js           │
   │   - /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/@nuxt/cli/dist/cli.js                   │
   │   - /home/nskoretz/Documents/Projects/nuxt-nsk/node_modules/nuxt/bin/nuxt.js                        │
   │                                                                                                     │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuxt-nsk@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nuxt-nsk@1.0.0 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nskoretz/.npm/_logs/2019-09-10T23_02_13_496Z-debug.log
```

This is similar to Issue #53 where `nuxt generate` "Cannot find a module".

## Further Information

The contents of my package.json, I only have nuxt, nuxt/press, and nuxt/press' peer dependencies installed.

```
{
  "name": "nuxt-nsk",
  "version": "1.0.0",
  "description": "Nicholas Skoretz online.",
  "author": "Nicholas Skoretz",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest"
  },
  "dependencies": {
    "@nuxt/press": "0.0.1-beta.4",
    "@nuxtjs/axios": "^4.5.2",
    "chokidar": "^3.0.2",
    "defu": "0.0.3",
    "defy": "^1.1.2",
    "nuxt": "^2.9.2"
  },
  "devDependencies": {
    "@vue/test-utils": "^1.0.0-beta.27",
    "markdownlint-cli": "^0.17.0"
  }
}
```

And from nuxt.config.js, the only modules that nuxt is using are the following...

```
  ** Nuxt.js dev-modules
  */
  devModules: [
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    '@nuxtjs/axios',
    '@nuxt/press'
  ],
```

Any thoughts on why it functions correctly on the dev server and not with `nuxt generate`? The other thread while encountering a similar problem didn't have a solution.

If more information is required, please feel free to ask. This is my first Bug Issue, so I'm not too sure what is required.

Thanks,

**Comment by pimlie** [comment]
It seems that the blog mode of nuxtpress is instantiated, which expect every md file to list a publishing date. If you only need to run md pages you can add nuxtpress to your modules as follows to make sure the blog mode is not loaded:
```
modules: [
  ...
  ['@nuxt/press', 'common']
]
```

Please note that the term `common` will change in the next beta release to `pages`

**Comment by nskoretz** [comment]
@pimlie Do you have any advice?

**Comment by pimlie** [comment]
@nskoretz Sorry, i dont have any clue. I really want to release the next beta this weekend at the latest, that will probably solve the issue and if not its easier to debug ;)

**Comment by nskoretz** [comment]
Alright, sounds good pimlie. I await the release.
